export const BLOCKED_ACCOUNTS: ReadonlySet<string> = new Set([
  "crystalfoxeth",
  "0xkevinrich",
  "tomcrypto_web3",
  "davidguapo",
  "wojaksx",
  "bullish__degen",
  "aytanzania",
]);

export function isBlockedAccount(username: string | null): boolean {
  if (!username) return false;
  return BLOCKED_ACCOUNTS.has(username.toLowerCase());
}

/** Headlines generated by the normalizer for contentless tweets (bare URLs, etc.) */
const JUNK_HEADLINES: ReadonlySet<string> = new Set([
  "link shared without context",
]);

export function isJunkHeadline(headline: string | null): boolean {
  if (!headline) return true;
  return JUNK_HEADLINES.has(headline.trim().toLowerCase());
}
