-- Adds operator feedback for generated story clusters.
-- Safe to run multiple times.

create table if not exists public.x_news_cluster_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  cluster_id bigint not null references public.x_news_clusters (id) on delete cascade,
  label text not null check (label in ('useful', 'noise', 'bad_cluster')),
  note text
);

create index if not exists x_news_cluster_feedback_cluster_created_idx
  on public.x_news_cluster_feedback (cluster_id, created_at desc);

