create table if not exists public.x_news_sources (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_type text not null check (source_type in ('account', 'keyword')),
  name text not null,
  query text,
  is_active boolean not null default true,
  notes text,
  constraint x_news_sources_type_name_key unique (source_type, name)
);
