-- Adds lightweight clustering tables for x-news normalized stories.
-- Safe to run multiple times.

create table if not exists public.x_news_clusters (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  normalized_headline text,
  normalized_facts jsonb not null default '[]'::jsonb,
  canonical_text text,
  token_set jsonb not null default '[]'::jsonb,
  tweet_count integer not null default 0,
  unique_user_count integer not null default 0,
  is_story_candidate boolean not null default false,
  merged_into_cluster_id bigint references public.x_news_clusters (id) on delete set null
);

create index if not exists x_news_clusters_active_last_seen_idx
  on public.x_news_clusters (last_seen_at desc)
  where merged_into_cluster_id is null;

create index if not exists x_news_clusters_story_candidates_last_seen_idx
  on public.x_news_clusters (last_seen_at desc)
  where merged_into_cluster_id is null and is_story_candidate = true;

create index if not exists x_news_clusters_merged_into_idx
  on public.x_news_clusters (merged_into_cluster_id);

create table if not exists public.x_news_cluster_tweets (
  tweet_id bigint primary key references public.tweets (id) on delete cascade,
  cluster_id bigint not null references public.x_news_clusters (id) on delete cascade,
  assigned_at timestamptz not null default now(),
  similarity_score double precision
);

create index if not exists x_news_cluster_tweets_cluster_id_idx
  on public.x_news_cluster_tweets (cluster_id);

create table if not exists public.x_news_cluster_merges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_cluster_id bigint not null references public.x_news_clusters (id) on delete cascade,
  target_cluster_id bigint not null references public.x_news_clusters (id) on delete cascade,
  similarity_score double precision,
  reason text
);

create index if not exists x_news_cluster_merges_target_idx
  on public.x_news_cluster_merges (target_cluster_id, created_at desc);
