-- Adds Chooserich-style tweet asset tables used by enrichment:
-- - tweet_images
-- - tweet_urls
-- - tweet_videos
--
-- Safe to run multiple times.

create table if not exists public.tweet_images (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tweet_id text,
  image_url text,
  warrants_financial_analysis boolean,
  image_category text,
  initial_claude_analysis jsonb,
  summary text,
  claude_summary_payload jsonb,
  constraint tweet_images_tweet_id_fkey
    foreign key (tweet_id) references public.tweets (tweet_id) on delete cascade
);

create unique index if not exists tweet_images_tweet_id_image_url_key
  on public.tweet_images (tweet_id, image_url);

create table if not exists public.tweet_urls (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tweet_id text,
  url text,
  url_content text,
  raw_url_content text,
  constraint tweet_urls_tweet_id_fkey
    foreign key (tweet_id) references public.tweets (tweet_id) on delete cascade
);

create unique index if not exists tweet_urls_tweet_id_url_key
  on public.tweet_urls (tweet_id, url);

create index if not exists tweet_urls_unprocessed_created_at_idx
  on public.tweet_urls (created_at desc)
  where url_content is null;

create table if not exists public.tweet_videos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tweet_id bigint not null,
  preview_image_url text,
  duration_ms integer,
  width integer,
  height integer,
  media_key text,
  url_320 text,
  url_480 text,
  url_720 text,
  url_1080 text,
  raw_variants jsonb,
  constraint tweet_videos_tweet_id_fkey
    foreign key (tweet_id) references public.tweets (id) on delete cascade
);

create unique index if not exists tweet_videos_tweet_id_media_key_key
  on public.tweet_videos (tweet_id, media_key);

