insert into public.x_news_sources (source_type, name)
values
  ('account', 'aggrnews'),
  ('account', 'ashcrypto'),
  ('account', 'autismcapital'),
  ('account', 'blockworks_'),
  ('account', 'bobloukas'),
  ('account', 'cointelegraph'),
  ('account', 'cryptohayes'),
  ('account', 'cryptoslate'),
  ('account', 'crypto_briefing'),
  ('account', 'deitaone'),
  ('account', 'decryptmedia'),
  ('account', 'degeneratenews'),
  ('account', 'ericbalchunas'),
  ('account', 'geiger_capital'),
  ('account', 'jseyff'),
  ('account', 'kobeissiletter'),
  ('account', 'luckytraderhq'),
  ('account', 'messaricrypto'),
  ('account', 'moonoverlord'),
  ('account', 'roundtablespace'),
  ('account', 'solanafloor'),
  ('account', 'techmeme'),
  ('account', 'theblockcampus'),
  ('account', 'theblock__'),
  ('account', 'thestalwart'),
  ('account', 'thetranscript_'),
  ('account', 'treenewsfeed'),
  ('account', 'tyler_did_it'),
  ('account', 'walterbloomberg'),
  ('account', 'watcherguru'),
  ('account', 'whaleinsider'),
  ('account', 'blocknewsdotcom'),
  ('account', 'bubblemaps'),
  ('account', 'coinbureau'),
  ('account', 'coingecko'),
  ('account', 'cryptodotnews'),
  ('account', 'cryptorover'),
  ('account', 'glassnode'),
  ('account', 'intangiblecoins'),
  ('account', 'ramahluwalia'),
  ('account', 'rektmando'),
  ('account', 'scottmelker'),
  ('account', 'solidintel_x'),
  ('account', 'tedtalksmacro'),
  ('account', 'tier10k'),
  ('account', 'tokenterminal'),
  ('account', 'unusual_whales'),
  ('account', 'xdaily'),
  ('account', 'xerocooleth'),
  ('account', 'zachxbt')
on conflict (source_type, name) do nothing;

insert into public.x_news_sources (source_type, name, query)
values (
  'keyword',
  'crypto-market-keywords',
  '"fed chair" OR "crypto market" OR "bitcoin" OR "market structure" OR "solana" OR "ethereum" OR "xrp" OR "brian armstrong" OR "coinbase" OR "okx" OR "kraken" OR "blockchain" OR "tether" lang:en min_faves:50 -filter:retweets'
)
on conflict (source_type, name) do nothing;
